//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Users = new HashSet<User>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Fax { get; set; }
        public string HeadName { get; set; }
        public string CollectionPoint { get; set; }
        public string CollectionTime { get; set; }
        public string Representative { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
