//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemAdjustments = new HashSet<ItemAdjustment>();
            this.PurchaseItems = new HashSet<PurchaseItem>();
            this.RequisitionItems = new HashSet<RequisitionItem>();
            this.SupplierItems = new HashSet<SupplierItem>();
        }
    
        public string ItemID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<int> CurrentQty { get; set; }
        public string CategoryName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Bin { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ItemAdjustment> ItemAdjustments { get; set; }
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
        public virtual ICollection<SupplierItem> SupplierItems { get; set; }
    }
}
