//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAdjustment
    {
        public string VoucherNo { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> AdjustedQty { get; set; }
        public string Reason { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Item Item { get; set; }
    }
}
