//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.PurchaseItems = new HashSet<PurchaseItem>();
        }
    
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string SupplierID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DONo { get; set; }
    
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
