//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItem
    {
        public string RequisitionID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> RequiredQty { get; set; }
        public Nullable<int> FulfilledQty { get; set; }
        public string FulfilledStatus { get; set; }
        public Nullable<int> AllocatedQty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
